project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: ""
  favicon: "plot/econ148-hex-logo.png"
  
  repo-url: https://github.com/econ148-analytical-stat-package
  site-url: https://econ148-analytical-stat-package.github.io/econ148-site/
  
  sidebar:
    style: docked
    pinned: true
    search: true
    tools:
      - icon: facebook
        href: https://www.facebook.com/viserdac/
      - icon: globe
        href: https://viserdac.vsu.edu.ph/
      - icon: github
        href: https://github.com/vsu-viserdac/impact-assessment
    
    contents:
      - href: "index.qmd"
        text: "**Home**"
      - href: "rp.qmd"
        text: "**Resource persons**"
      - section: "**Day 1 sessions**"
        contents:
          - href: "01-L1-intro-impact-assessment.qmd"
            text: "Lecture 1: Introduction to Impact Assessment"
          - href: "02-L1-theory-of-change.qmd"
            text: "Lecture 2: Validating theory of change"
          - href: "03-L3-dev-impact-pathways.qmd"
            text: "Lecture 3: Development of impact pathway and adoption studies"
          - href: "10-W1-impact-pathway.qmd"
            text: "Workshop 1: Developing the impact pathway"

      
      - section: "**Day 2 sessions**"
        contents:
          - href: "04-L4-intro-stata.qmd"
            text: "Lecture 4: Introduction to Stata/R software"
          - href: "11-W2-application-stata.qmd"
            text: "Workshop 2: use and application of Stata/R"
          - href: "05-L5-analytical-methods-adoption-studies.qmd"
            text: "Lecture 5: Analytical methods for adoption studies"
          - href: ""
            text: "Workshop 3: Adoption studies"
          - href: ""
            text: "Lecture 6: Cost-benefit analysis"
            
      
      - section: "**Day 3 sessions**"
        contents:
          - href: "07-L7-impact-estimation-psm.qmd"
            text: "Lecture 7: Impact estimation using PSM"
          - href: ""
            text: "Workshop 4: propensity score matching (PSM"
          - href: "08-L8-impact-estimation-did.qmd"
            text: "Lecture 8: Impact estimation using DiD method"
          - href: ""
            text: "Workshop 5: Difference-in-differences (DiD)"
          - href: "09-L9-mixed-methods-ia.qmd"
            text: "Lecture 9: Mixed methods approach to IA"
      
format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: false

freeze: auto
editor: visual

